### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by harryiitd** [Call-for-Code/weather-api-python#5]
For the link: https://twcservice.mybluemix.net/rest-api/#/

Trying any of the links on the page is giving "no response from the server" as error with a '0' response code. Please suggest how could this be resolved.

Thank You!

**Comment by vabarbosa** [comment]
@harryiitd my apologies for the late response. i completely missed this issue.

if you are trying to use the Weather Company Data Service. unfortunately it is no longer available. however, the Weather Company API Platform is available. if you are interested in participating in the [Call for Code Global Challenge](https://developer.ibm.com/callforcode/blogs/call-for-code-the-weather-company-and-you/), it is now open. you can register for an API Key and get free access to [some of the Weather APIs](https://weather.com/swagger-docs/call-for-code).

let me know if you have any question or have a different issue.
again my apologies for not getting to this sooner.
