### ISSUE TITLE
Weather Company Data service does not exist - remove line that references it

### ISSUE THREAD

**Issue by kwiatks** [Call-for-Code/weather-api-python#6]
Remove line "All others, sign up for IBM Cloud here and provision the Weather Company Data service. The Weather Company Data service uses slightly different API versions. You can reference its documentation here." since the Weather Company Data service no longer exists.

**Comment by vabarbosa** [comment]
@kwiatks thanks for the heads up
https://github.com/Call-for-Code/weather-api-python/pull/7
